"""Pydantic schemas for request/response validation."""

from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    UserDetailResponse,
    UserPasswordChange,
)
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    ChangePasswordRequest,
    MessageResponse as AuthMessageResponse,
    UserMeResponse,
)
from app.schemas.business import (
    BusinessCreate,
    BusinessUpdate,
    BusinessOnboardingUpdate,
    BusinessResponse,
    BusinessDetailResponse,
    BusinessListResponse,
)
from app.schemas.common import (
    HealthCheckResponse,
    ErrorResponse,
    SuccessResponse,
    MessageResponse,
    PaginationParams,
    FilterParams,
)
from app.schemas.bank_import import (
    BankImportCreate,
    BankImportResponse,
    BankImportListResponse,
    BankTransactionResponse,
    BankTransactionListResponse,
    ColumnMappingRequest,
    ColumnDetectionResponse,
    ReconciliationSuggestion,
    ReconciliationMatch,
    MatchRequest,
    UnmatchRequest,
    IgnoreRequest,
    ReconciliationStats,
)
from app.schemas.support import (
    TicketCreate,
    TicketUpdate,
    TicketResponse,
    TicketDetailResponse,
    TicketListResponse,
    MessageCreate,
    MessageResponse,
    TicketWithBusinessContext,
    SupportStatsResponse,
    CannedResponseResponse,
    CannedResponseListResponse,
    TicketFilters,
    TicketRatingUpdate,
)
from app.schemas.help import (
    FaqCategoryResponse,
    FaqCategoryListResponse,
    FaqArticleResponse,
    FaqArticleListResponse,
    FaqSearchRequest,
    HelpArticleResponse,
    HelpArticleSummaryResponse,
    HelpArticleListResponse,
    HelpArticleFilters,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "UserDetailResponse",
    "UserPasswordChange",
    # Auth schemas
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "ChangePasswordRequest",
    "AuthMessageResponse",
    "UserMeResponse",
    # Business schemas
    "BusinessCreate",
    "BusinessUpdate",
    "BusinessOnboardingUpdate",
    "BusinessResponse",
    "BusinessDetailResponse",
    "BusinessListResponse",
    # Common schemas
    "HealthCheckResponse",
    "ErrorResponse",
    "SuccessResponse",
    "MessageResponse",
    "PaginationParams",
    "FilterParams",
    # Bank import schemas
    "BankImportCreate",
    "BankImportResponse",
    "BankImportListResponse",
    "BankTransactionResponse",
    "BankTransactionListResponse",
    "ColumnMappingRequest",
    "ColumnDetectionResponse",
    "ReconciliationSuggestion",
    "ReconciliationMatch",
    "MatchRequest",
    "UnmatchRequest",
    "IgnoreRequest",
    "ReconciliationStats",
    # Support schemas
    "TicketCreate",
    "TicketUpdate",
    "TicketResponse",
    "TicketDetailResponse",
    "TicketListResponse",
    "MessageCreate",
    "MessageResponse",
    "TicketWithBusinessContext",
    "SupportStatsResponse",
    "CannedResponseResponse",
    "CannedResponseListResponse",
    "TicketFilters",
    "TicketRatingUpdate",
    # Help schemas
    "FaqCategoryResponse",
    "FaqCategoryListResponse",
    "FaqArticleResponse",
    "FaqArticleListResponse",
    "FaqSearchRequest",
    "HelpArticleResponse",
    "HelpArticleSummaryResponse",
    "HelpArticleListResponse",
    "HelpArticleFilters",
]
